name: robomongo-snap
version: v1.4.4
summary: Robo 3T
base: core20

description: |
  Robo 3T (formerly Robomongo) is the free lightweight GUI for MongoDB enthusiasts.
  MongoDB GUI with embedded shell.

type: app

confinement: strict

icon: snap/gui/icon.png

grade: stable

architectures: [amd64]

apps:
    robo3t-snap:
        command: bin/robo3t
        plugs: 
          - home
          - x11
          - unity7
          - desktop
          - network
          - network-bind
        extensions:
          - kde-neon

parts:
    tarball:
        plugin: dump
        source: https://github.com/Studio3T/robomongo/releases/download/v1.4.4/robo3t-1.4.4-linux-x86_64-e6ac9ec.tar.gz
        stage-packages:
          - libcurl3-gnutls